load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build/kernel/kleaf:kernel.bzl",
    "initramfs",
    "kernel_module_group",
    "kernel_modules_install",
    "vendor_boot_image",
    "vendor_dlkm_image",
)

def define_imx_ddk_evk_95_images():
    kernel_module_group(
        name = "imx_evk_95_vendor_boot_modules",
        srcs = [
            #imx_evk_95_vendor_boot_modules
            ":hwmon",
            ":scmi-hwmon",
            ":imx-sm-lmm",
            ":imx-sm-cpu",
            ":imx-sm-bbm",
            ":imx-sm-misc",
            ":scmi_power_control",
            ":arm_smmu_v3",
            ":clk-scmi",
            ":mxc-clk",
            ":clk-imx95-blk-ctl",
            ":timer-imx-sysctr",
            ":imx-mailbox",
            ":rpmsg_ns",
            ":virtio_rpmsg_bus",
            ":sm-cpu",
            ":sm-lmm",
            ":imx_rproc",
            ":pinctrl-imx",
            ":pinctrl-imx-scmi",
            ":fsl-edma",
            ":fsl_lpuart_95",
            ":trusty-core",
            ":trusty-log",
            ":trusty-ipc",
            ":trusty-virtio",
            ":i2c-imx-lpi2c",
            ":i2c-dev",
            ":i2c-rpmsg-imx",
            ":i2c-mux",
            ":irq-imx-irqsteer",
            ":rtc-imx-sm-bbm",
            ":sm-misc",
            ":cpufreq-dt",
            ":imx7ulp_wdt",
            ":sec_enclave",
            ":cqhci",
            ":busfreq-imx8mq",
            ":sdhci-esdhc-imx",
            ":nvmem-imx-ocotp",
            ":nvmem-imx-ocotp-fsb-s400",
            ":pwrseq_simple",
            ":pwm-imx-tpm",
            ":soc-imx9",
            ":gpio-adp5585",
            ":gpio-pca953x",
            ":gpio-vf610",
            ":led_bl",
            ":pwm_bl",
            ":system_heap",
            ":dsp_heap",
            ":cma_heap",
            ":dma-buf-imx",
            ":maxim_serdes",
            ":max96752-core",
            ":max96752-i2c",
            ":adp5585",
            ":max96789-core",
            ":max96789-i2c",
            ":dummy_battery",
            ":pwm-adp5585",
            ":phy-fsl-imx8mq-usb",
            ":focaltech_ts",
            ":ilitek_ts_i2c",
            ":exc3000",
            ":imx-sm-bbm-key",
            ":usbmisc_imx",
            ":ulpi",
            ":ci_hdrc_imx",
            ":ci_hdrc",
            ":phy-generic",
            ":dwc3-imx8mp",
            ":gpio-switch",
            ":mux-core",
            ":mux-mmio",
            ":phy-fsl-imx9-dphy-rx",
            ":phy-fsl-imx8mp-lvds",
            ":linux_logo",
            ":fb",
            ":fb_notify",
            ":cfbcopyarea",
            ":fb_io_fops",
            ":fb_sys_fops",
            ":sysimgblt",
            ":syscopyarea",
            ":sysfillrect",
            ":cfbfillrect",
            ":cfbimgblt",
            ":drm_fbdev_helper",
            ":drm_dma_helper",
            ":it6161",
            ":max96752-lvds",
            ":display-connector",
            ":adv7511",
            ":fsl-imx-ldb",
            ":max96789-dsi",
            ":it6263",
            ":ti-sn65dsi83",
            ":nwl-dsi",
            ":lontium-lt8912b",
            ":lontium-lt9611uxc",
            ":imx95-pixel-link",
            ":imx95-pixel-interleaver",
            ":imx-ldb-helper",
            ":imx95-ldb",
            ":dw-mipi-dsi",
            ":imx95-mipi-dsi",
            ":imx-lcdif",
            ":panel-raydium-rm67191",
            ":panel-nxp-rm67162",
            ":panel-simple",
            ":panel-raydium-rm692c9",
            ":panel-rocktech-hx8394f",
            ":panel-lvds",
            ":drm_display_helper",
            ":imx95-dpu-drm",
            ":display-imx-rpmsg",
            ":imx8-isi",
            ":imx-csi-formatter",
            ":dwc-mipi-csi2",
        ],
        visibility = ["//visibility:public"],
    )

    kernel_modules_install(
        name = "imx_evk_95_vendor_boot_modules_install",
        kernel_build = ":imx_ddk_modules",
        kernel_modules = [
            ":imx_evk_95_vendor_boot_modules",
        ],
    )

    _IMX_EVK_95_AARCH64_VENDOR_BOOT_FIRST_STAGE_MODULES_LIST = [
        "hwmon.ko",
        "scmi-hwmon.ko",
        "imx-sm-lmm.ko",
        "imx-sm-cpu.ko",
        "imx-sm-bbm.ko",
        "imx-sm-misc.ko",
        "scmi_power_control.ko",
        "arm_smmu_v3.ko",
        "clk-scmi.ko",
        "mxc-clk.ko",
        "clk-imx95-blk-ctl.ko",
        "timer-imx-sysctr.ko",
        "imx-mailbox.ko",
        "rpmsg_ns.ko",
        "virtio_rpmsg_bus.ko",
        "sm-cpu.ko",
        "sm-lmm.ko",
        "imx_rproc.ko",
        "pinctrl-imx.ko",
        "pinctrl-imx-scmi.ko",
        "fsl-edma.ko",
        "fsl_lpuart_95.ko",
        "trusty-core.ko",
        "trusty-log.ko",
        "trusty-ipc.ko",
        "trusty-virtio.ko",
        "i2c-imx-lpi2c.ko",
        "i2c-dev.ko",
        "i2c-rpmsg-imx.ko",
        "i2c-mux.ko",
        "irq-imx-irqsteer.ko",
        "rtc-imx-sm-bbm.ko",
        "sm-misc.ko",
        "cpufreq-dt.ko",
        "imx7ulp_wdt.ko",
        "sec_enclave.ko",
        "cqhci.ko",
        "busfreq-imx8mq.ko",
        "sdhci-esdhc-imx.ko",
        "nvmem-imx-ocotp.ko",
        "nvmem-imx-ocotp-fsb-s400.ko",
        "pwrseq_simple.ko",
        "pwm-imx-tpm.ko",
        "soc-imx9.ko",
        "gpio-adp5585.ko",
        "gpio-pca953x.ko",
        "gpio-vf610.ko",
    ]

    _IMX_EVK_95_AARCH64_VENDOR_BOOT_RECOVERY_FIRST_STAGE_ADDITION_MODULES_LIST = [
        "led_bl.ko",
        "pwm_bl.ko",
        "system_heap.ko",
        "dsp_heap.ko",
        "cma_heap.ko",
        "dma-buf-imx.ko",
        "maxim_serdes.ko",
        "max96752-core.ko",
        "max96752-i2c.ko",
        "adp5585.ko",
        "max96789-core.ko",
        "max96789-i2c.ko",
        "dummy_battery.ko",
        "pwm-adp5585.ko",
        "phy-fsl-imx8mq-usb.ko",
        "focaltech_ts.ko",
        "ilitek_ts_i2c.ko",
        "exc3000.ko",
        "imx-sm-bbm-key.ko",
        "usbmisc_imx.ko",
        "ulpi.ko",
        "ci_hdrc_imx.ko",
        "ci_hdrc.ko",
        "phy-generic.ko",
        "dwc3-imx8mp.ko",
        "gpio-switch.ko",
        "mux-core.ko",
        "mux-mmio.ko",
        "phy-fsl-imx9-dphy-rx.ko",
        "phy-fsl-imx8mp-lvds.ko",
        "linux_logo.ko",
        "fb.ko",
        "fb_notify.ko",
        "cfbcopyarea.ko",
        "fb_io_fops.ko",
        "fb_sys_fops.ko",
        "sysimgblt.ko",
        "syscopyarea.ko",
        "sysfillrect.ko",
        "cfbfillrect.ko",
        "cfbimgblt.ko",
        "drm_fbdev_helper.ko",
        "drm_dma_helper.ko",
        "it6161.ko",
        "max96752-lvds.ko",
        "display-connector.ko",
        "adv7511.ko",
        "fsl-imx-ldb.ko",
        "max96789-dsi.ko",
        "it6263.ko",
        "ti-sn65dsi83.ko",
        "nwl-dsi.ko",
        "lontium-lt8912b.ko",
        "lontium-lt9611uxc.ko",
        "imx95-pixel-link.ko",
        "imx95-pixel-interleaver.ko",
        "imx-ldb-helper.ko",
        "imx95-ldb.ko",
        "dw-mipi-dsi.ko",
        "imx95-mipi-dsi.ko",
        "imx-lcdif.ko",
        "panel-raydium-rm67191.ko",
        "panel-nxp-rm67162.ko",
        "panel-simple.ko",
        "panel-raydium-rm692c9.ko",
        "panel-rocktech-hx8394f.ko",
        "panel-lvds.ko",
        "drm_display_helper.ko",
        "imx95-dpu-drm.ko",
        "display-imx-rpmsg.ko",
        "imx8-isi.ko",
        "imx-csi-formatter.ko",
        "dwc-mipi-csi2.ko",
    ]

    write_file(
        name = "imx_evk_95_aarch64_vendor_boot_modules_list",
        out = "modules_list.imx_evk_95_aarch64",
        content = _IMX_EVK_95_AARCH64_VENDOR_BOOT_FIRST_STAGE_MODULES_LIST,
    )

    write_file(
        name = "imx_evk_95_aarch64_vendor_boot_modules_recovery_list",
        out = "modules_recovery_list.imx_evk_95_aarch64",
        content = _IMX_EVK_95_AARCH64_VENDOR_BOOT_FIRST_STAGE_MODULES_LIST + _IMX_EVK_95_AARCH64_VENDOR_BOOT_RECOVERY_FIRST_STAGE_ADDITION_MODULES_LIST,
    )

    write_file(
        name = "imx_evk_95_aarch64_vendor_dlkm_modules_charger_list",
        out = "modules_charger_list.imx_evk_95_aarch64",
        content = _IMX_EVK_95_AARCH64_VENDOR_BOOT_FIRST_STAGE_MODULES_LIST + _IMX_EVK_95_AARCH64_VENDOR_BOOT_RECOVERY_FIRST_STAGE_ADDITION_MODULES_LIST,
    )

    initramfs(
        name = "imx_evk_95_aarch64_initramfs",
        kernel_modules_install = ":imx_evk_95_vendor_boot_modules_install",
        modules_charger_list = ":modules_charger_list.imx_evk_95_aarch64",
        modules_list = ":modules_list.imx_evk_95_aarch64",
        modules_recovery_list = ":modules_recovery_list.imx_evk_95_aarch64",
        vendor_boot_name = "vendor_boot",
        trim_unused_modules = True,
    )

    vendor_boot_image(
        name = "imx_evk_95_aarch64_vendor_boot_image",
        outs = [
            "ramdisk.lz4",
        ],
        initramfs = ":imx_evk_95_aarch64_initramfs",
        kernel_build = ":imx_ddk_modules",
        unpack_ramdisk = True,
        ramdisk_compression = "lz4",
        vendor_boot_name = "vendor_boot",
    )

    kernel_module_group(
        name = "imx_evk_95_vendor_dlkm_modules",
        srcs = [
            #imx_evk_95_vendor_dlkm_modules
            ":led_bl",
            ":pwm_bl",
            ":system_heap",
            ":dsp_heap",
            ":cma_heap",
            ":dma-buf-imx",
            ":maxim_serdes",
            ":max96752-core",
            ":max96752-i2c",
            ":adp5585",
            ":max96789-core",
            ":max96789-i2c",
            ":dummy_battery",
            ":pwm-adp5585",
            ":phy-fsl-imx8mq-usb",
            ":focaltech_ts",
            ":ilitek_ts_i2c",
            ":exc3000",
            ":imx-sm-bbm-key",
            ":usbmisc_imx",
            ":ulpi",
            ":ci_hdrc_imx",
            ":ci_hdrc",
            ":phy-generic",
            ":dwc3-imx8mp",
            ":gpio-switch",
            ":mux-core",
            ":mux-mmio",
            ":phy-fsl-imx9-dphy-rx",
            ":phy-fsl-imx8mp-lvds",
            ":linux_logo",
            ":fb",
            ":fb_notify",
            ":cfbcopyarea",
            ":fb_io_fops",
            ":fb_sys_fops",
            ":sysimgblt",
            ":syscopyarea",
            ":sysfillrect",
            ":cfbfillrect",
            ":cfbimgblt",
            ":drm_fbdev_helper",
            ":drm_dma_helper",
            ":it6161",
            ":max96752-lvds",
            ":display-connector",
            ":adv7511",
            ":fsl-imx-ldb",
            ":max96789-dsi",
            ":it6263",
            ":ti-sn65dsi83",
            ":nwl-dsi",
            ":lontium-lt8912b",
            ":lontium-lt9611uxc",
            ":imx95-pixel-link",
            ":imx95-pixel-interleaver",
            ":imx-ldb-helper",
            ":imx95-ldb",
            ":dw-mipi-dsi",
            ":imx95-mipi-dsi",
            ":imx-lcdif",
            ":panel-raydium-rm67191",
            ":panel-nxp-rm67162",
            ":panel-simple",
            ":panel-raydium-rm692c9",
            ":panel-rocktech-hx8394f",
            ":panel-lvds",
            ":drm_display_helper",
            ":imx95-dpu-drm",
            ":display-imx-rpmsg",
            ":imx8-isi",
            ":imx-csi-formatter",
            ":dwc-mipi-csi2",
            ":ap1302",
            ":ox03c10",
            ":max96717_lib",
            ":mx95mbcam",
            ":max96724",
            ":libarc4",
            ":fsl_imx9_ddr_perf",
            ":imx93_adc",
            ":gpio-reset",
            ":imx-sm-reset",
            ":pci-imx6",
            ":spidev",
            ":spi-bitbang",
            ":spi-nxp-fspi",
            ":spi-fsl-lpspi",
            ":mtd",
            ":spi-nor",
            ":leds-gpio",
            ":leds-pca995x",
            ":leds-pca963x",
            ":memory_usage",
            ":wave6-vpu-ctrl",
            ":wave6",
            ":v4l2-cci",
            ":ox05b1s",
            ":v4l2-jpeg",
            ":mxc-jpeg-encdec",
            ":neoisp",
            ":imx-pcm-dma",
            ":imx-pcm-rpmsg",
            ":snd-soc-fsl-utils",
            ":snd-soc-dmic",
            ":snd-soc-fsl-micfil",
            ":snd-soc-fsl-mqs",
            ":snd-soc-fsl-asrc",
            ":snd-soc-fsl-sai",
            ":snd-soc-bt-sco",
            ":snd-soc-simple-card-utils",
            ":snd-soc-simple-card",
            ":snd-soc-audio-graph-card2",
            ":snd-soc-imx-card",
            ":snd-soc-imx-audmux",
            ":snd-soc-imx-rpmsg",
            ":snd-soc-fsl-asoc-card",
            ":imx-audio-rpmsg",
            ":snd-soc-fsl-rpmsg",
            ":snd-soc-ak4458",
            ":snd-soc-ak5558",
            ":snd-soc-wm8962",
            ":snd-soc-wm8904",
            ":snd-soc-cs42xx8",
            ":snd-soc-cs42xx8-i2c",
            ":aquantia",
            ":pps_core",
            ":ptp",
            ":nxp-netc-lib",
            ":nxp-netc-blk-ctrl",
            ":ptp_netc",
            ":ptp-qoriq",
            ":fsl-enetc-ptp",
            ":pcs-lynx",
            ":pcs_xpcs",
            ":fsl-enetc-mdio",
            ":fsl-enetc-core",
            ":crc-itu-t",
            ":fsl-enetc-vf",
            ":fsl-enetc4",
            ":realtek",
            "//nxp-mwifiex:mlan",
            "//nxp-mwifiex:moal",
            ":imx_neutron_rproc",
            ":neutron",
            ":mali_kbase",
            ":pwm-fan",
        ],
        visibility = ["//visibility:public"],
    )

    kernel_modules_install(
        name = "imx_evk_95_vendor_dlkm_modules_install",
        kernel_build = ":imx_ddk_modules",
        kernel_modules = [
            ":imx_evk_95_vendor_dlkm_modules",
        ],
    )

    _IMX_EVK_95_AARCH64_VENDOR_DLKM_MODULES_LIST = [
        "ap1302.ko",
        "ox03c10.ko",
        "max96717_lib.ko",
        "mx95mbcam.ko",
        "max96724.ko",
        "cfg80211.ko",
        "libarc4.ko",
        "mac80211.ko",
        "fsl_imx9_ddr_perf.ko",
        "imx93_adc.ko",
        "gpio-reset.ko",
        "imx-sm-reset.ko",
        "pci-imx6.ko",
        "spidev.ko",
        "spi-bitbang.ko",
        "spi-nxp-fspi.ko",
        "spi-fsl-lpspi.ko",
        "mtd.ko",
        "spi-nor.ko",
        "leds-gpio.ko",
        "leds-pca995x.ko",
        "leds-pca963x.ko",
        "memory_usage.ko",
        "wave6-vpu-ctrl.ko",
        "wave6.ko",
        "v4l2-cci.ko",
        "ox05b1s.ko",
        "v4l2-jpeg.ko",
        "mxc-jpeg-encdec.ko",
        "neoisp.ko",
        "imx-pcm-dma.ko",
        "imx-pcm-rpmsg.ko",
        "snd-soc-fsl-utils.ko",
        "snd-soc-dmic.ko",
        "snd-soc-fsl-micfil.ko",
        "snd-soc-fsl-mqs.ko",
        "snd-soc-fsl-asrc.ko",
        "snd-soc-fsl-sai.ko",
        "snd-soc-bt-sco.ko",
        "snd-soc-simple-card-utils.ko",
        "snd-soc-simple-card.ko",
        "snd-soc-audio-graph-card2.ko",
        "snd-soc-imx-card.ko",
        "snd-soc-imx-audmux.ko",
        "snd-soc-imx-rpmsg.ko",
        "snd-soc-fsl-asoc-card.ko",
        "imx-audio-rpmsg.ko",
        "snd-soc-fsl-rpmsg.ko",
        "snd-soc-ak4458.ko",
        "snd-soc-ak5558.ko",
        "snd-soc-wm8962.ko",
        "snd-soc-wm8904.ko",
        "snd-soc-cs42xx8.ko",
        "snd-soc-cs42xx8-i2c.ko",
        "aquantia.ko",
        "pps_core.ko",
        "ptp.ko",
        "nxp-netc-lib.ko",
        "nxp-netc-blk-ctrl.ko",
        "ptp_netc.ko",
        "ptp-qoriq.ko",
        "fsl-enetc-ptp.ko",
        "pcs-lynx.ko",
        "pcs_xpcs.ko",
        "fsl-enetc-mdio.ko",
        "fsl-enetc-core.ko",
        "crc-itu-t.ko",
        "fsl-enetc-vf.ko",
        "fsl-enetc4.ko",
        "realtek.ko",
        "mlan.ko",
        "moal.ko",
        "imx_neutron_rproc.ko",
        "neutron.ko",
        "mali_kbase.ko",
        "pwm-fan.ko",
    ]

    write_file(
        name = "imx_evk_95_aarch64_vendor_dlkm_modules_list",
        out = "modules_list.imx_evk_95_aarch64_vendor_dlkm",
        content = _IMX_EVK_95_AARCH64_VENDOR_BOOT_RECOVERY_FIRST_STAGE_ADDITION_MODULES_LIST + _IMX_EVK_95_AARCH64_VENDOR_DLKM_MODULES_LIST,
    )

    vendor_dlkm_image(
        name = "imx_evk_95_aarch64_vendor_dlkm_image",
        archive = True,
        kernel_modules_install = ":imx_evk_95_vendor_dlkm_modules_install",
        modules_list = ":imx_evk_95_aarch64_vendor_dlkm_modules_list",
        fs_type = "erofs",
    )

    # Package vendor_boot image files
    pkg_files(
        name = "imx_evk_95_aarch64_vendor_boot_dist_files",
        srcs = [
            ":imx_evk_95_aarch64_vendor_boot_image",
        ],
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )

    # Install vendor_boot image to output directory
    pkg_install(
        name = "imx_evk_95_aarch64_vendor_boot_dist",
        srcs = [":imx_evk_95_aarch64_vendor_boot_dist_files"],
        destdir = "out/imx_evk_95_aarch64/dist",
    )

    # Package vendor_dlkm image files
    pkg_files(
        name = "imx_evk_95_aarch64_vendor_dlkm_dist_files",
        srcs = [
            ":imx_evk_95_aarch64_vendor_dlkm_image",
        ],
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )

    # Install vendor_dlkm image to output directory
    pkg_install(
        name = "imx_evk_95_aarch64_vendor_dlkm_dist",
        srcs = [":imx_evk_95_aarch64_vendor_dlkm_dist_files"],
        destdir = "out/imx_evk_95_aarch64/dist",
    )
