load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build/kernel/kleaf:kernel.bzl",
    "initramfs",
    "kernel_module_group",
    "kernel_modules_install",
    "vendor_boot_image",
    "vendor_dlkm_image",
)

def define_imx_ddk_evk_8mm_images():
    kernel_module_group(
        name = "imx_evk_8mm_vendor_boot_modules",
        srcs = [
            #imx_evk_8mm_vendor_boot_modules
            ":mxc-clk",
            ":clk-imx8mm",
            ":soc-imx8m",
            ":imx8m-blk-ctrl",
            ":imx8m_pm_domains",
            ":gpcv2",
            ":gpcv2-imx",
            ":timer-imx-sysctr",
            ":busfreq-imx8mq",
            ":pinctrl-imx",
            ":pinctrl-imx8mm",
            ":imx-tty",
            ":imx2_wdt",
            ":pca9450-regulator",
            ":gpio-mxc",
            ":fsl_imx8_ddr_perf",
            ":rohm-bd718x7",
            ":rohm-regulator",
            ":bd718x7-regulator",
            ":cpufreq-dt",
            ":imx-cpufreq-dt",
            ":nvmem-imx-ocotp",
            ":cqhci",
            ":sdhci-esdhc-imx",
            ":i2c-imx",
            ":i2c-dev",
            ":spidev",
            ":spi-bitbang",
            ":spi-nxp-fspi",
            ":spi-imx",
            ":stmp_device",
            ":mxs-dma",
            ":pwrseq_simple",
            ":imx-mailbox",
            ":system_heap",
            ":cma_heap",
            ":dma-buf-imx",
            ":snvs_pwrkey",
            ":goodix_ts",
            ":synaptics_dsx_i2c",
            ":reset-dispmix",
            ":reset-imx7",
            ":linux_logo",
            ":fb",
            ":fb_notify",
            ":cfbcopyarea",
            ":fb_io_fops",
            ":fb_sys_fops",
            ":sysimgblt",
            ":syscopyarea",
            ":sysfillrect",
            ":cfbfillrect",
            ":cfbimgblt",
            ":drm_fbdev_helper",
            ":imx8mm-lcdif-core",
            ":drm_dma_helper",
            ":adv7511",
            ":sec-dsim",
            ":imxdrm",
            ":imx8mm-lcdif-crtc",
            ":panel-raydium-rm67191",
            ":sec_mipi_dsim-imx",
            ":usbmisc_imx",
            ":ulpi",
            ":ci_hdrc_imx",
            ":ci_hdrc",
            ":phy-generic",
            ":dummy_battery",
            ":imx-sdma",
            ":trusty-core",
            ":trusty-log",
            ":trusty-ipc",
            ":trusty-virtio",
        ],
        visibility = ["//visibility:public"],
    )

    kernel_modules_install(
        name = "imx_evk_8mm_vendor_boot_modules_install",
        kernel_build = ":imx_ddk_modules",
        kernel_modules = [
            ":imx_evk_8mm_vendor_boot_modules",
        ],
    )

    _IMX_EVK_8MM_AARCH64_VENDOR_BOOT_MODULES_LIST = [
        "mxc-clk.ko",
        "clk-imx8mm.ko",
        "soc-imx8m.ko",
        "imx8m-blk-ctrl.ko",
        "imx8m_pm_domains.ko",
        "gpcv2.ko",
        "gpcv2-imx.ko",
        "timer-imx-sysctr.ko",
        "busfreq-imx8mq.ko",
        "pinctrl-imx.ko",
        "pinctrl-imx8mm.ko",
        "imx.ko",
        "imx2_wdt.ko",
        "pca9450-regulator.ko",
        "gpio-mxc.ko",
        "fsl_imx8_ddr_perf.ko",
        "rohm-bd718x7.ko",
        "rohm-regulator.ko",
        "bd718x7-regulator.ko",
        "cpufreq-dt.ko",
        "imx-cpufreq-dt.ko",
        "nvmem-imx-ocotp.ko",
        "cqhci.ko",
        "sdhci-esdhc-imx.ko",
        "i2c-imx.ko",
        "i2c-dev.ko",
        "spidev.ko",
        "spi-bitbang.ko",
        "spi-nxp-fspi.ko",
        "spi-imx.ko",
        "stmp_device.ko",
        "mxs-dma.ko",
        "pwrseq_simple.ko",
        "imx-mailbox.ko",
        "system_heap.ko",
        "cma_heap.ko",
        "dma-buf-imx.ko",
        "snvs_pwrkey.ko",
        "goodix_ts.ko",
        "synaptics_dsx_i2c.ko",
        "reset-dispmix.ko",
        "reset-imx7.ko",
        "linux_logo.ko",
        "fb_notify.ko",
        "fb.ko",
        "cfbcopyarea.ko",
        "fb_io_fops.ko",
        "fb_sys_fops.ko",
        "sysimgblt.ko",
        "syscopyarea.ko",
        "sysfillrect.ko",
        "cfbfillrect.ko",
        "cfbimgblt.ko",
        "drm_fbdev_helper.ko",
        "imx8mm-lcdif-core.ko",
        "drm_dma_helper.ko",
        "adv7511.ko",
        "sec-dsim.ko",
        "imxdrm.ko",
        "imx8mm-lcdif-crtc.ko",
        "panel-raydium-rm67191.ko",
        "sec_mipi_dsim-imx.ko",
        "usbmisc_imx.ko",
        "ulpi.ko",
        "ci_hdrc_imx.ko",
        "ci_hdrc.ko",
        "phy-generic.ko",
        "dummy_battery.ko",
        "imx-sdma.ko",
        "trusty-core.ko",
        "trusty-log.ko",
        "trusty-ipc.ko",
        "trusty-virtio.ko",
    ]

    write_file(
        name = "imx_evk_8mm_aarch64_vendor_boot_modules_list",
        out = "modules_list.imx_evk_8mm_aarch64",
        content = _IMX_EVK_8MM_AARCH64_VENDOR_BOOT_MODULES_LIST,
    )

    write_file(
        name = "imx_evk_8mm_aarch64_vendor_boot_modules_recovery_list",
        out = "modules_recovery_list.imx_evk_8mm_aarch64",
        content = _IMX_EVK_8MM_AARCH64_VENDOR_BOOT_MODULES_LIST,
    )

    write_file(
        name = "imx_evk_8mm_aarch64_vendor_dlkm_modules_charger_list",
        out = "modules_charger_list.imx_evk_8mm_aarch64",
        content = _IMX_EVK_8MM_AARCH64_VENDOR_BOOT_MODULES_LIST,
    )

    initramfs(
        name = "imx_evk_8mm_aarch64_initramfs",
        kernel_modules_install = ":imx_evk_8mm_vendor_boot_modules_install",
        modules_charger_list = ":modules_charger_list.imx_evk_8mm_aarch64",
        modules_list = ":modules_list.imx_evk_8mm_aarch64",
        modules_recovery_list = ":modules_recovery_list.imx_evk_8mm_aarch64",
        vendor_boot_name = "vendor_boot",
        trim_unused_modules = True,
    )

    vendor_boot_image(
        name = "imx_evk_8mm_aarch64_vendor_boot_image",
        outs = [
            "ramdisk.lz4",
        ],
        initramfs = ":imx_evk_8mm_aarch64_initramfs",
        kernel_build = ":imx_ddk_modules",
        unpack_ramdisk = True,
        ramdisk_compression = "lz4",
        vendor_boot_name = "vendor_boot",
    )

    kernel_module_group(
        name = "imx_evk_8mm_vendor_dlkm_modules",
        srcs = [
            #imx_evk_8mm_vendor_dlkm_modules
            ":galcore",
            ":imx8mm_thermal",
            ":imx7-media-csi",
            ":imx-mipi-csis",
            ":ov5640",
            ":leds-gpio",
            ":leds-pca995x",
            ":gpio-pca953x",
            ":imx-pcm-dma",
            ":snd-soc-fsl-utils",
            ":snd-soc-fsl-micfil",
            ":snd-soc-fsl-asrc",
            ":snd-soc-fsl-easrc",
            ":snd-soc-fsl-sai",
            ":snd-soc-fsl-spdif",
            ":snd-soc-imx-audmux",
            ":snd-soc-fsl-asoc-card",
            ":snd-soc-simple-card-utils",
            ":snd-soc-wm8524",
            ":snd-soc-ak4458",
            ":snd-soc-ak5558",
            ":snd-soc-bt-sco",
            ":snd-soc-simple-card",
            ":rpmsg_ns",
            ":virtio_rpmsg_bus",
            ":sm-cpu",
            ":sm-lmm",
            ":imx_rproc",
            ":i2c-rpmsg-imx",
            ":imx-pcm-rpmsg",
            ":snd-soc-fsl-rpmsg",
            ":imx-audio-rpmsg",
            ":snd-soc-rpmsg-ak4497",
            ":snd-soc-imx-rpmsg",
            ":snd-soc-imx-card",
            ":hantrodec_845s",
            ":hx280enc",
            ":memory_usage",
            ":vsiv4l2",
            ":rtc-snvs",
            ":qcom-phy-lib",
            ":at803x",
            ":realtek",
            ":pps_core",
            ":ptp",
            ":fec",
            #mwifiex
            "//nxp-mwifiex:mlan",
            "//nxp-mwifiex:moal",

            # vvcam
            "//verisilicon_sw_isp_vvcam/vvcam:vvcam-dwe",
            "//verisilicon_sw_isp_vvcam/vvcam:vvcam-isp",
            "//verisilicon_sw_isp_vvcam/vvcam:vvcam-video",
            "//verisilicon_sw_isp_vvcam/vvcam:os08a20",
            "//verisilicon_sw_isp_vvcam/vvcam:basler-camera-driver-vvcam",
        ],
        visibility = ["//visibility:public"],
    )

    kernel_modules_install(
        name = "imx_evk_8mm_vendor_dlkm_modules_install",
        kernel_build = ":imx_ddk_modules",
        kernel_modules = [
            ":imx_evk_8mm_vendor_dlkm_modules",
        ],
    )

    _IMX_EVK_8MM_AARCH64_VENDOR_DLKM_MODULES_LIST = [
        "galcore.ko",
        "imx8mm_thermal.ko",
        "imx7-media-csi.ko",
        "imx-mipi-csis.ko",
        "ov5640.ko",
        "leds-gpio.ko",
        "leds-pca995x.ko",
        "gpio-pca953x.ko",
        "imx-pcm-dma.ko",
        "snd-soc-fsl-utils.ko",
        "snd-soc-fsl-micfil.ko",
        "snd-soc-fsl-asrc.ko",
        "snd-soc-fsl-easrc.ko",
        "snd-soc-fsl-sai.ko",
        "snd-soc-fsl-spdif.ko",
        "snd-soc-imx-audmux.ko",
        "snd-soc-fsl-asoc-card.ko",
        "snd-soc-simple-card-utils.ko",
        "snd-soc-wm8524.ko",
        "snd-soc-ak4458.ko",
        "snd-soc-ak5558.ko",
        "snd-soc-bt-sco.ko",
        "snd-soc-simple-card.ko",
        "rpmsg_ns.ko",
        "virtio_rpmsg_bus.ko",
        "sm-cpu.ko",
        "sm-lmm.ko",
        "imx_rproc.ko",
        "i2c-rpmsg-imx.ko",
        "imx-pcm-rpmsg.ko",
        "snd-soc-fsl-rpmsg.ko",
        "imx-audio-rpmsg.ko",
        "snd-soc-rpmsg-ak4497.ko",
        "snd-soc-imx-rpmsg.ko",
        "snd-soc-imx-card.ko",
        "hantrodec_845s.ko",
        "hx280enc.ko",
        "memory_usage.ko",
        "vsiv4l2.ko",
        "rtc-snvs.ko",
        "qcom-phy-lib.ko",
        "at803x.ko",
        "realtek.ko",
        "pps_core.ko",
        "ptp.ko",
        "fec.ko",
        "cfg80211.ko",
        "mac80211.ko",
        "mlan.ko",
        "moal.ko",
        "vvcam-dwe.ko",
        "vvcam-isp.ko",
        "vvcam-video.ko",
        "os08a20.ko",
        "basler-camera-driver-vvcam.ko",
    ]

    write_file(
        name = "imx_evk_8mm_aarch64_vendor_dlkm_modules_list",
        out = "modules_list.imx_evk_8mm_aarch64_vendor_dlkm",
        content = _IMX_EVK_8MM_AARCH64_VENDOR_DLKM_MODULES_LIST,
    )

    vendor_dlkm_image(
        name = "imx_evk_8mm_aarch64_vendor_dlkm_image",
        archive = True,
        kernel_modules_install = ":imx_evk_8mm_vendor_dlkm_modules_install",
        modules_list = ":imx_evk_8mm_aarch64_vendor_dlkm_modules_list",
        fs_type = "erofs",
    )

    # Package vendor_boot image files
    pkg_files(
        name = "imx_evk_8mm_aarch64_vendor_boot_dist_files",
        srcs = [
            ":imx_evk_8mm_aarch64_vendor_boot_image",
        ],
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )

    # Install vendor_boot image to output directory
    pkg_install(
        name = "imx_evk_8mm_aarch64_vendor_boot_dist",
        srcs = [":imx_evk_8mm_aarch64_vendor_boot_dist_files"],
        destdir = "out/imx_evk_8mm_aarch64/dist",
    )

    # Package vendor_dlkm image files
    pkg_files(
        name = "imx_evk_8mm_aarch64_vendor_dlkm_dist_files",
        srcs = [
            ":imx_evk_8mm_aarch64_vendor_dlkm_image",
        ],
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )

    # Install vendor_dlkm image to output directory
    pkg_install(
        name = "imx_evk_8mm_aarch64_vendor_dlkm_dist",
        srcs = [":imx_evk_8mm_aarch64_vendor_dlkm_dist_files"],
        destdir = "out/imx_evk_8mm_aarch64/dist",
    )
