/* SPDX-License-Identifier: GPL-2.0+ */

/*
 * Copyright 2026 NXP
 */

#ifndef __DPU95_LD_REGS_H__
#define __DPU95_LD_REGS_H__

/* Clock control register 0 */
#define LD_REG_CLKCTRL0			0x8
#define CLKCTRL0_GLOBCLKEN		BIT(0)

/* Clock control register 1 */
#define LD_REG_CLKCTRL1			0xC
#define CLKCTRL1_CLKLDSYSEN		BIT(1)
#define CLKCTRL1_CLKLDEN		BIT(0)

/* Horizontal Internal Sync Timing */
#define LD_REG_HSYNCTIMING		0x20
#define HSYNC_SRT_MASK			GENMASK(13, 0)
#define HSYNC_SRT_SET(n)		FIELD_PREP(HSYNC_SRT_MASK, n)

/* Vertical Internal Sync Timing */
#define LD_REG_VSYNCTIMING		0x24
#define VSYNC_END_MASK			GENMASK(29, 16)
#define VSYNC_END_SET(n)		FIELD_PREP(VSYNC_END_MASK, n)
#define VSYNC_SRT_MASK			GENMASK(13, 0)
#define VSYNC_SRT_SET(n)		FIELD_PREP(VSYNC_SRT_MASK, n)

/* Static Control */
#define LD_REG_STATICCONTROL		0x1C
#define STATICCONTROL_MODE_MASK		GENMASK(13, 12)
#define STATICCONTROL_MODE_SET(n)	FIELD_PREP(STATICCONTROL_MODE_MASK, n)
#define STATICCONTROL_DEPOL		BIT(10)
#define STATICCONTROL_VPPOL		BIT(9)
#define STATICCONTROL_HPPOL		BIT(8)
#define STATICCONTROL_DLYCMP_MASK	GENMASK(7, 1)
#define STATICCONTROL_DLYCMP_SET(n)	FIELD_PREP(STATICCONTROL_DLYCMP_MASK, n)
#define STATICCONTROL_BYPASS		BIT(0)

/* Localdimming/ldupreg000: */
#define LD_REG_LDUPREG000		0x1080

/* Localdimming/ldhifreg00a: */
#define LD_REG_LDHIFREG00A		0x1028
#define LDHIFREG00A_LDVINTDLY_MASK	GENMASK(12, 0)
#define LDHIFREG00A_LDVINTDLY_SET(n)	FIELD_PREP(LDHIFREG00A_LDVINTDLY_MASK, n)
#define LDHIFREG00A_LDVINTDLY_GET(n)	FIELD_GET(LDHIFREG00A_LDVINTDLY_MASK, n)

/* Localdimming/ldhifreg00b: */
#define LD_REG_LDHIFREG00B		0x102C
#define LDHIFREG00B_SMSLVON_SET(n)	FIELD_PREP(BIT(10), n)
#define LDHIFREG00B_SMVLVON_SET(n)	FIELD_PREP(BIT(9), n)
#define LDHIFREG00B_SMBLVON_SET(n)	FIELD_PREP(BIT(8), n)
#define LDHIFREG00B_VINTON_SET(n)	FIELD_PREP(BIT(2), n)
#define LDHIFREG00B_LEDINTON_SET(n)	FIELD_PREP(BIT(1), n)
#define LDHIFREG00B_BLINTON_SET(n)	FIELD_PREP(BIT(0), n)

#endif
