#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

cmd="$1"

rename_syms() {
	local original_obj=$1
	local renamed_obj=$2

	# Generate a file which contains the original and new names for all
	# necessary symbols. This will be used by the objcopy to rename symbols.
	$NM $original_obj |
	# Remove duplicated symbol names
	$AWK '!seen[$NF]++ {print $NF}' |
	# Filter out the names which contain:
	# __x86_return_thunk
	# __x86_indirect_
	# The instructions using these symbols are generated by the compiler.
	# Leave them alone to satisfy the objtool and the boot time patching for
	# retpoline and return thunk. However filtering out also means their
	# definition won't be renamed as well. Thus will need manually renaming
	# done by the patch_retpoline().
	$AWK '!/__x86_return_thunk/ && !/^__x86_indirect_/' |
	# Rename the filtered symbols following below rules:
	# 1) if a symbol name contains ".", which means it is generated by the
	# compiler, add __pkvm suffix before the first "." to keep the compiler's
	# suffix in place, e.g.: *.cold -> *__pkvm.cold.
	# 2) otherwise if a symbol name starts with "__pkvm___x86_indirect_",
	# which means it is generated by patch_retpoline() below, remove the
	# first 7 characters and add "__pkvm" suffix.
	# 3) otherwise just add "__pkvm" suffix.
	#
	# The reason we add __pkvm as a suffix, not a prefix, is to not conflict
	# with other prefixes like __cfi which objtool and other tools rely on.
	$AWK '{
		idx = index($1, ".");
		if (idx > 0) {
			print $1, substr($1, 1, idx-1)"__pkvm"substr($1, idx)
		} else {
			idx = index($1, "__pkvm___x86_indirect_");
			if (idx == 1) {
				print $1, substr($1, 8)"__pkvm"
			} else {
				print $1, $1"__pkvm"
			}
		}
	}' > $renamed_obj.syms;

	# Rename symbols for the original object according to the generated file
	$OBJCOPY --redefine-syms=$renamed_obj.syms $original_obj $renamed_obj;

	rm -f $renamed_obj.syms
}

patch_retpoline() {
	local retpoline_in=$1
	local retpoline_out=$2

	echo "/* Automatically generated from $retpoline_in. DO NOT MODIFY directly! */
	" > $retpoline_out;

	# Manually rename the defined symbols in the retpoline.S filter out by
	# rename_syms().
	# 1) Add __pkvm suffix to the __x86_return_thunk to have
	# __x86_return_thunk__pkvm
	# 2) Add __pkvm prefix to the defined symbols starting with
	# __x86_indirect_. This would be renamed by the renamed_syms() to
	# __x86_indirect_xxxx__pkvm. Adding as prefix here can avoid modifying
	# the macro generates the symbols __x86_indirect_xxxx
	#
	# The reason of manually renaming rather than using rename_syms() is
	# that the retpoline.S itself has the asm code "jmp __x86_return_thunk"
	# which will be patched by the kernel at the boot time as well. This
	# symbol name should be retained, like what the rename_syms() does to
	# filter out __x86_return_thunk. However the __x86_return_thunk function
	# is also defined in retpoline.S and this function should be renamed. To
	# satisfy this, manually rename the symbols in the retpoline.S.
	sed 's/\(\<__x86_return_thunk\>\)/\1__pkvm/g;
	     s/\(__x86_indirect_\)/__pkvm_\1/g' $retpoline_in >> $retpoline_out
}

case "$cmd" in
	rename_syms)
		if [ $# -ne 3 ];then
			echo "Usage: $0 rename_syms <input object> <output object>"
			exit 1
		fi
		rename_syms $2 $3;;
	patch_retpoline)
		if [ $# -ne 3 ];then
			echo "Usage: $0 patch_retpoline <input retpoline.S> <output retpoline file>"
			exit 1
		fi
		patch_retpoline $2 $3;;
	*)	die "Unknown command: $cmd";;
esac
