# STMP3XXX platfrom support
snd-soc-stmp3xxx-objs := stmp3xxx_pcm.o
snd-soc-stmp3xxx-dai-objs := stmp3xxx_dai.o
snd-soc-stmp3xxx-spdif-dai-objs := stmp3xxx_spdif_dai.o
snd-soc-stmp3780-devb-objs := stmp3780_devb.o
snd-soc-stmp3780-devb-spdif-objs := stmp3780_devb_spdif.o

obj-$(CONFIG_SND_STMP3XXX_SOC) += snd-soc-stmp3xxx.o
obj-$(CONFIG_SND_STMP3XXX_SOC_DAI) += snd-soc-stmp3xxx-dai.o
obj-$(CONFIG_SND_STMP3XXX_SOC_SPDIF_DAI) += snd-soc-stmp3xxx-spdif-dai.o
obj-$(CONFIG_SND_STMP3XXX_SOC_STMP3780_DEVB) += snd-soc-stmp3780-devb.o
obj-$(CONFIG_SND_STMP3XXX_SOC_STMP3780_DEVB_SPDIF) += snd-soc-stmp3780-devb-spdif.o
