# SPDX-License-Identifier: GPL-2.0

$(obj)/hyp.lds: arch/arm64/kvm/hyp/nvhe/module.lds.S FORCE
	$(call if_changed_dep,cpp_lds_S)

include $(srctree)/arch/arm64/kvm/hyp/nvhe/Makefile.nvhe

# LINT.IfChange(includes)
ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/module
# LINT.ThenChange(/BUILD.bazel:pkvm_includes)

ccflags-y += -DMODULE
