obj-$(CONFIG_MTD_NAND_GPMI) += gpmi.o
gpmi-objs += gpmi-base.o gpmi-bbt.o
gpmi-objs += gpmi-hamming-22-16.o
gpmi-objs += gpmi-hamming-13-8.o
gpmi-objs += gpmi-bch.o
gpmi-objs += gpmi-ecc8.o
gpmi-objs += nand_device_info.o
