/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Coda series multi-standard codec IP - product config definitions
 *
 * Copyright (C) 2024-2026 CHIPS&MEDIA INC
 */

#ifndef __CODA_VPUCONFIG_H__
#define __CODA_VPUCONFIG_H__

#include "coda-vdi.h"

#define CODA980_CODE 0x9800

#define CODA_VPU_TIMEOUT 6000

#define CODA_MAX_FBS 32

#define CODA_MIN_FRAME_BUFFER_NUM 2

#define CODA_ENC_DEF_PIC_WIDTH 416U
#define CODA_ENC_DEF_PIC_HEIGHT 240U
#define CODA_ENC_MIN_PIC_WIDTH 96U
#define CODA_ENC_MAX_PIC_WIDTH 4096U
#define CODA_ENC_MIN_PIC_HEIGHT 16U
#define CODA_ENC_MAX_PIC_HEIGHT 4096U
#define CODA_ENC_CODEC_PIC_STEP 8U
#define CODA_ENC_RAW_PIC_STEP 8U
#define CODA_ENC_CROP_X_POS_STEP 32
#define CODA_ENC_CROP_Y_POS_STEP 2
#define CODA_ENC_CROP_STEP 2

#define CODA_SDRAM_SIZE (4 * 1024)
#define CODA_CODE_BUF_SIZE (272 * 1024)
#define CODA_TEMP_BUF_SIZE (470 * 1024)
#define CODA_MAX_CODE_BUF_SIZE (512 * 1024)
#define CODA_SIZE_COMMON (1 * 1024 * 1024)
#define CODA_WORK_BUF_SIZE (80 * 1024)
#define CODA_REPORT_BUF_SIZE_ADDR_INFO (32)
#define CODA_REPORT_BUF_SIZE_MB_INFO \
	((CODA_ENC_MAX_PIC_WIDTH / 16) * (CODA_ENC_MAX_PIC_HEIGHT / 16))
#define CODA_REPORT_BUF_SIZE_MV_INFO (CODA_REPORT_BUF_SIZE_MB_INFO * 4)
#define CODA_REPORT_BUF_SIZE_SLICE_INFO (CODA_REPORT_BUF_SIZE_MB_INFO * 8)
#define CODA_REPORT_BUF_SIZE_COST_INFO (CODA_REPORT_BUF_SIZE_MB_INFO * 8)

#endif
