/* SPDX-License-Identifier: GPL-2.0-only OR MIT */
/*
 * Copyright 2026 NXP
 */

#ifndef __DT_BINDINGS_CLOCK_IMX952_H
#define __DT_BINDINGS_CLOCK_IMX952_H

#define IMX952_CLK_DISPMIX_LVDS_PHY_DIV		0
#define IMX952_CLK_DISPMIX_LVDS_CH0_GATE	1
#define IMX952_CLK_DISPMIX_LVDS_CH1_GATE	2
#define IMX952_CLK_DISPMIX_PIX_DI0_GATE		3
#define IMX952_CLK_DISPMIX_PIX_DI1_GATE		4

#endif	/* __DT_BINDINGS_CLOCK_IMX952_H */
