# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_NET_DSA_NETC_SWITCH) += nxp-netc-switch.o
nxp-netc-switch-objs := netc_main.o netc_platform.o netc_tc.o \
			netc_ethtool.o netc_ptp.o
nxp-netc-switch-$(CONFIG_DEBUG_FS) += netc_debugfs.o
