# SPDX-License-Identifier: GPL-2.0
# Makefile for staging directory

obj-y				+= media/
obj-$(CONFIG_RTL8723BS)		+= rtl8723bs/
obj-$(CONFIG_OCTEON_ETHERNET)	+= octeon/
obj-$(CONFIG_VME_BUS)		+= vme_user/
obj-$(CONFIG_IIO)		+= iio/
obj-$(CONFIG_FB_SM750)		+= sm750fb/
obj-$(CONFIG_MFD_NVEC)		+= nvec/
obj-$(CONFIG_FB_TFT)		+= fbtft/
obj-$(CONFIG_MOST)		+= most/
obj-$(CONFIG_GREYBUS)		+= greybus/
obj-$(CONFIG_BCM2835_VCHIQ)	+= vc04_services/
obj-$(CONFIG_FSL_SDK_DPA)	+= fsl_qbman/
obj-$(CONFIG_FSL_DPAA2)		+= fsl-dpaa2/
obj-$(CONFIG_XIL_AXIS_FIFO)	+= axis-fifo/
obj-$(CONFIG_GPIB)	 	+= gpib/
obj-$(CONFIG_FSL_PPFE)		+= fsl_ppfe/
obj-$(CONFIG_ETHOSU)		+= ethosu/
obj-$(CONFIG_NEUTRON)		+= neutron/

obj-$(CONFIG_ASHMEM)		+= android/
