/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 *
 * (C) COPYRIGHT 2025-2026 ARM Limited. All rights reserved.
 *
 * This program is free software and is provided to you under the terms of the
 * GNU General Public License version 2 as published by the Free Software
 * Foundation, and any use by you of this program is subject to the terms
 * of such GNU license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you can access it online at
 * http://www.gnu.org/licenses/gpl-2.0.html.
 *
 */

#ifndef _MALI_KBASE_AM_REG_IPA_H_
#define _MALI_KBASE_AM_REG_IPA_H_

#include <hw_access/mali_kbase_hw_access_regmap.h>

#include <linux/types.h>

/* Register base and size */
#define GOV_IPA_REG_BASE (IPA_CONTROL__COMMAND)
#define GOV_IPA_REG_BASE_NX (GPU_GOVERNOR__GOV_IPA_CONTROL__SELECT_NEURAL)
#define GOV_IPA_REG_SIZE (IPA_CONTROL__VALUE_SHADER_7 - GOV_IPA_REG_BASE + 1)
#define GOV_IPA_REG_SIZE_NX \
	(GPU_GOVERNOR__GOV_IPA_CONTROL__VALUE_NEURAL_7 - GOV_IPA_REG_BASE_NX + 1)

/* Packed enum mapping table */
#define GOV_IPA_REG_GET_FLAT_IDX(reg_enum) (reg_enum - GOV_IPA_REG_BASE)
#define GOV_IPA_REG_GET_FLAT_IDX_NX(reg_enum) (reg_enum - GOV_IPA_REG_BASE_NX + GOV_IPA_REG_SIZE)
#define GOV_IPA_REG_VAL(reg_name) \
	GOV_IPA_REG_GET_FLAT_IDX(GPU_GOVERNOR__GOV_IPA_CONTROL__##reg_name)
#define GOV_IPA_REG_VAL_NX(reg_name) \
	GOV_IPA_REG_GET_FLAT_IDX_NX(GPU_GOVERNOR__GOV_IPA_CONTROL__##reg_name)

enum {
	GOV_IPA_REG__COMMAND = GOV_IPA_REG_VAL(COMMAND),
	GOV_IPA_REG__SELECT_CSHW = GOV_IPA_REG_VAL(SELECT_CSHW),
	GOV_IPA_REG__SELECT_MEMSYS = GOV_IPA_REG_VAL(SELECT_MEMSYS),
	GOV_IPA_REG__SELECT_SHADER = GOV_IPA_REG_VAL(SELECT_SHADER),
	GOV_IPA_REG__SELECT_TILER = GOV_IPA_REG_VAL(SELECT_TILER),
	GOV_IPA_REG__STATUS = GOV_IPA_REG_VAL(STATUS),
	GOV_IPA_REG__TIMER = GOV_IPA_REG_VAL(TIMER),
	GOV_IPA_REG__VALUE_CSHW_0 = GOV_IPA_REG_VAL(VALUE_CSHW_0),
	GOV_IPA_REG__VALUE_CSHW_1 = GOV_IPA_REG_VAL(VALUE_CSHW_1),
	GOV_IPA_REG__VALUE_CSHW_2 = GOV_IPA_REG_VAL(VALUE_CSHW_2),
	GOV_IPA_REG__VALUE_CSHW_3 = GOV_IPA_REG_VAL(VALUE_CSHW_3),
	GOV_IPA_REG__VALUE_CSHW_4 = GOV_IPA_REG_VAL(VALUE_CSHW_4),
	GOV_IPA_REG__VALUE_CSHW_5 = GOV_IPA_REG_VAL(VALUE_CSHW_5),
	GOV_IPA_REG__VALUE_CSHW_6 = GOV_IPA_REG_VAL(VALUE_CSHW_6),
	GOV_IPA_REG__VALUE_CSHW_7 = GOV_IPA_REG_VAL(VALUE_CSHW_7),
	GOV_IPA_REG__VALUE_MEMSYS_0 = GOV_IPA_REG_VAL(VALUE_MEMSYS_0),
	GOV_IPA_REG__VALUE_MEMSYS_1 = GOV_IPA_REG_VAL(VALUE_MEMSYS_1),
	GOV_IPA_REG__VALUE_MEMSYS_2 = GOV_IPA_REG_VAL(VALUE_MEMSYS_2),
	GOV_IPA_REG__VALUE_MEMSYS_3 = GOV_IPA_REG_VAL(VALUE_MEMSYS_3),
	GOV_IPA_REG__VALUE_MEMSYS_4 = GOV_IPA_REG_VAL(VALUE_MEMSYS_4),
	GOV_IPA_REG__VALUE_MEMSYS_5 = GOV_IPA_REG_VAL(VALUE_MEMSYS_5),
	GOV_IPA_REG__VALUE_MEMSYS_6 = GOV_IPA_REG_VAL(VALUE_MEMSYS_6),
	GOV_IPA_REG__VALUE_MEMSYS_7 = GOV_IPA_REG_VAL(VALUE_MEMSYS_7),
	GOV_IPA_REG__VALUE_SHADER_0 = GOV_IPA_REG_VAL(VALUE_SHADER_0),
	GOV_IPA_REG__VALUE_SHADER_1 = GOV_IPA_REG_VAL(VALUE_SHADER_1),
	GOV_IPA_REG__VALUE_SHADER_2 = GOV_IPA_REG_VAL(VALUE_SHADER_2),
	GOV_IPA_REG__VALUE_SHADER_3 = GOV_IPA_REG_VAL(VALUE_SHADER_3),
	GOV_IPA_REG__VALUE_SHADER_4 = GOV_IPA_REG_VAL(VALUE_SHADER_4),
	GOV_IPA_REG__VALUE_SHADER_5 = GOV_IPA_REG_VAL(VALUE_SHADER_5),
	GOV_IPA_REG__VALUE_SHADER_6 = GOV_IPA_REG_VAL(VALUE_SHADER_6),
	GOV_IPA_REG__VALUE_SHADER_7 = GOV_IPA_REG_VAL(VALUE_SHADER_7),
	GOV_IPA_REG__VALUE_TILER_0 = GOV_IPA_REG_VAL(VALUE_TILER_0),
	GOV_IPA_REG__VALUE_TILER_1 = GOV_IPA_REG_VAL(VALUE_TILER_1),
	GOV_IPA_REG__VALUE_TILER_2 = GOV_IPA_REG_VAL(VALUE_TILER_2),
	GOV_IPA_REG__VALUE_TILER_3 = GOV_IPA_REG_VAL(VALUE_TILER_3),
	GOV_IPA_REG__VALUE_TILER_4 = GOV_IPA_REG_VAL(VALUE_TILER_4),
	GOV_IPA_REG__VALUE_TILER_5 = GOV_IPA_REG_VAL(VALUE_TILER_5),
	GOV_IPA_REG__VALUE_TILER_6 = GOV_IPA_REG_VAL(VALUE_TILER_6),
	GOV_IPA_REG__VALUE_TILER_7 = GOV_IPA_REG_VAL(VALUE_TILER_7),
	GOV_IPA_REG__SELECT_NEURAL = GOV_IPA_REG_VAL_NX(SELECT_NEURAL),
	GOV_IPA_REG__VALUE_NEURAL_0 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_0),
	GOV_IPA_REG__VALUE_NEURAL_1 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_1),
	GOV_IPA_REG__VALUE_NEURAL_2 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_2),
	GOV_IPA_REG__VALUE_NEURAL_3 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_3),
	GOV_IPA_REG__VALUE_NEURAL_4 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_4),
	GOV_IPA_REG__VALUE_NEURAL_5 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_5),
	GOV_IPA_REG__VALUE_NEURAL_6 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_6),
	GOV_IPA_REG__VALUE_NEURAL_7 = GOV_IPA_REG_VAL_NX(VALUE_NEURAL_7),
};

#endif /* _MALI_KBASE_AM_REG_IPA_H_ */
